// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProArena.Infrastructure.Data.Context;

#nullable disable

namespace ProArena.Infrastructure.Migrations
{
    [DbContext(typeof(ProArenaContext))]
    [Migration("20260221223142_att-usuario")]
    partial class attusuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EquipeJogador", b =>
                {
                    b.Property<int>("EquipesEquipeId")
                        .HasColumnType("int");

                    b.Property<int>("JogadoresJogadorId")
                        .HasColumnType("int");

                    b.HasKey("EquipesEquipeId", "JogadoresJogadorId");

                    b.HasIndex("JogadoresJogadorId");

                    b.ToTable("EquipeJogador");
                });

            modelBuilder.Entity("EquipePartida", b =>
                {
                    b.Property<int>("EquipeId")
                        .HasColumnType("int");

                    b.Property<int>("PartidasPartidaId")
                        .HasColumnType("int");

                    b.HasKey("EquipeId", "PartidasPartidaId");

                    b.HasIndex("PartidasPartidaId");

                    b.ToTable("EquipePartida");
                });

            modelBuilder.Entity("ProArena.Domain.Entities.Campeonato", b =>
                {
                    b.Property<int>("CampeonatoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CampeonatoId"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataFimInscricao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInicioInscricao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CampeonatoId");

                    b.ToTable("Campeonatos");
                });

            modelBuilder.Entity("ProArena.Domain.Entities.Equipe", b =>
                {
                    b.Property<int>("EquipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipeId"));

                    b.Property<int?>("CampeonatoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("EquipeId");

                    b.ToTable("Equipes");
                });

            modelBuilder.Entity("ProArena.Domain.Entities.Inscricao", b =>
                {
                    b.Property<int>("InscricaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InscricaoId"));

                    b.Property<int>("CampeonatoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataInscricao")
                        .HasColumnType("datetime2");

                    b.Property<int>("EquipeId")
                        .HasColumnType("int");

                    b.HasKey("InscricaoId");

                    b.HasIndex("CampeonatoId");

                    b.HasIndex("EquipeId");

                    b.ToTable("Inscricao");
                });

            modelBuilder.Entity("ProArena.Domain.Entities.Jogador", b =>
                {
                    b.Property<int>("JogadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JogadorId"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("JogadorId");

                    b.ToTable("Jogadores");
                });

            modelBuilder.Entity("ProArena.Domain.Entities.Partida", b =>
                {
                    b.Property<int>("PartidaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PartidaId"));

                    b.Property<int>("CampeonatoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("EquipeId")
                        .HasColumnType("int");

                    b.HasKey("PartidaId");

                    b.HasIndex("CampeonatoId");

                    b.ToTable("Partidas");
                });

            modelBuilder.Entity("ProArena.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nome")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("int");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("EquipeJogador", b =>
                {
                    b.HasOne("ProArena.Domain.Entities.Equipe", null)
                        .WithMany()
                        .HasForeignKey("EquipesEquipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProArena.Domain.Entities.Jogador", null)
                        .WithMany()
                        .HasForeignKey("JogadoresJogadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EquipePartida", b =>
                {
                    b.HasOne("ProArena.Domain.Entities.Equipe", null)
                        .WithMany()
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProArena.Domain.Entities.Partida", null)
                        .WithMany()
                        .HasForeignKey("PartidasPartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProArena.Domain.Entities.Inscricao", b =>
                {
                    b.HasOne("ProArena.Domain.Entities.Campeonato", "Campeonato")
                        .WithMany("Inscricoes")
                        .HasForeignKey("CampeonatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProArena.Domain.Entities.Equipe", "Equipe")
                        .WithMany("Inscricao")
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campeonato");

                    b.Navigation("Equipe");
                });

            modelBuilder.Entity("ProArena.Domain.Entities.Partida", b =>
                {
                    b.HasOne("ProArena.Domain.Entities.Campeonato", "Campeonato")
                        .WithMany("Partidas")
                        .HasForeignKey("CampeonatoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campeonato");
                });

            modelBuilder.Entity("ProArena.Domain.Entities.Campeonato", b =>
                {
                    b.Navigation("Inscricoes");

                    b.Navigation("Partidas");
                });

            modelBuilder.Entity("ProArena.Domain.Entities.Equipe", b =>
                {
                    b.Navigation("Inscricao");
                });
#pragma warning restore 612, 618
        }
    }
}
