// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProArena.Infrastructure.Data.Context;

#nullable disable

namespace ProArena.Infrastructure.Migrations
{
    [DbContext(typeof(ProArenaContext))]
    partial class ProArenaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EquipeJogador", b =>
                {
                    b.Property<int>("EquipesEquipeId")
                        .HasColumnType("int");

                    b.Property<int>("JogadoresJogadorId")
                        .HasColumnType("int");

                    b.HasKey("EquipesEquipeId", "JogadoresJogadorId");

                    b.HasIndex("JogadoresJogadorId");

                    b.ToTable("EquipeJogador");
                });

            modelBuilder.Entity("ProArena.Domain.Entities.Campeonato", b =>
                {
                    b.Property<int>("CampeonatoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CampeonatoId"));

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CampeonatoId");

                    b.ToTable("Campeonatos");
                });

            modelBuilder.Entity("ProArena.Domain.Entities.Equipe", b =>
                {
                    b.Property<int>("EquipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipeId"));

                    b.Property<int?>("CampeonatoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("EquipeId");

                    b.HasIndex("CampeonatoId");

                    b.ToTable("Equipes");
                });

            modelBuilder.Entity("ProArena.Domain.Entities.Jogador", b =>
                {
                    b.Property<int>("JogadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JogadorId"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("JogadorId");

                    b.ToTable("Jogadores");
                });

            modelBuilder.Entity("ProArena.Domain.Entities.Partida", b =>
                {
                    b.Property<int>("PartidaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PartidaId"));

                    b.Property<int?>("CampeonatoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("EquipeAId")
                        .HasColumnType("int");

                    b.Property<int>("EquipeBId")
                        .HasColumnType("int");

                    b.Property<int>("ResultadoEquipeA")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("ResultadoEquipeB")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.HasKey("PartidaId");

                    b.HasIndex("CampeonatoId");

                    b.HasIndex("EquipeAId");

                    b.HasIndex("EquipeBId");

                    b.ToTable("Partidas");
                });

            modelBuilder.Entity("EquipeJogador", b =>
                {
                    b.HasOne("ProArena.Domain.Entities.Equipe", null)
                        .WithMany()
                        .HasForeignKey("EquipesEquipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProArena.Domain.Entities.Jogador", null)
                        .WithMany()
                        .HasForeignKey("JogadoresJogadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProArena.Domain.Entities.Equipe", b =>
                {
                    b.HasOne("ProArena.Domain.Entities.Campeonato", "Campeonato")
                        .WithMany("Equipes")
                        .HasForeignKey("CampeonatoId");

                    b.Navigation("Campeonato");
                });

            modelBuilder.Entity("ProArena.Domain.Entities.Partida", b =>
                {
                    b.HasOne("ProArena.Domain.Entities.Campeonato", null)
                        .WithMany("Partidas")
                        .HasForeignKey("CampeonatoId");

                    b.HasOne("ProArena.Domain.Entities.Equipe", "EquipeA")
                        .WithMany()
                        .HasForeignKey("EquipeAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProArena.Domain.Entities.Equipe", "EquipeB")
                        .WithMany()
                        .HasForeignKey("EquipeBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EquipeA");

                    b.Navigation("EquipeB");
                });

            modelBuilder.Entity("ProArena.Domain.Entities.Campeonato", b =>
                {
                    b.Navigation("Equipes");

                    b.Navigation("Partidas");
                });
#pragma warning restore 612, 618
        }
    }
}
